function varargout = tabPanelExample()
%TABPANELEXAMPLE Tab panel example with callbacks
% This example shows how to use tabs within a layout. It also shows how to
% use the SelectionChangedFcn callback property of the uix.TabPanel layout
% to update other user-interface elements when the visible tab is changed.

% Copyright 2009-2024 The MathWorks, Inc.

%% Create a new figure window.
% Create a new figure window and remove the toolbar and menus.
f = figure( 'Name', 'Tab Panel Example', ...
    'MenuBar', 'none', ...
    'Toolbar', 'none', ...
    'NumberTitle', 'off' );

%% Define the application layout.
% The layout involves two panels side by side. This is done using a
% flexible horizontal box. The left-hand side is filled with a standard
% panel and the right-hand side with a tab panel.
hbf = uix.HBoxFlex( 'Parent', f, ...
    'Spacing', 10 );
p = uix.Panel( 'Parent', hbf, ...
    'Padding', 5, ...
    'Title', 'List Box Control' );
tp = uix.TabPanel( 'Parent', hbf, ...
    'Padding', 0 );

%% Add a listbox on the left.
% Note that we link the listbox callback to the tab selection, and the tab
% panel selection changed callback to the listbox such that they are kept
% in sync.
lb = uicontrol( 'Parent', p, ...
    'Style', 'list', ...
    'String', {'List Item 1', 'List Item 2', 'List Item 3'}, ...    
    'Callback', @(s, ~) set( tp, 'Selection', s.Value ) );
tp.SelectionChangedFcn = @(~, e) set( lb, 'Value', e.NewValue );

%% Add the tab contents.
% We fill each tab with a panel containing a numbered button.
p1 = uix.Panel( 'Parent', tp, ...
    'Padding', 5, ...
    'Title', 'Panel 1' );
uicontrol( 'Parent', p1, ...
    'Style', 'pushbutton', ...
    'String', 'Button 1', ...
    'FontSize', 25, ...
    'FontWeight', 'bold' )
p2 = uix.Panel( 'Parent', tp, ...
    'Padding', 5, ...
    'Title', 'Panel 2' );
uicontrol( 'Parent', p2, ...
    'Style', 'pushbutton', ...
    'String', 'Button 2', ...
    'FontSize', 25, ...
    'FontWeight', 'bold' )
p3 = uix.Panel( 'Parent', tp, ...
    'Padding', 5, ...
    'Title', 'Panel 3' );
uicontrol( 'Parent', p3, ...
    'Style', 'pushbutton', ...
    'String', 'Button 3', ...
    'FontSize', 25, ...
    'FontWeight', 'bold' )

%% Update the tab titles.
tp.TabTitles = {'Tab 1', 'Tab 2', 'Tab 3'};

%% Return the figure if an output is requested.
nargoutchk( 0, 1 )
if nargout == 1
    varargout{1} = f;
end % if

end % tabPanelExample